services:
  sonarstagingbackend:
    image: dimagin/sonar-back:staging
    container_name: sonar-staging-back
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      sonarstagingdatabase:
        condition: service_healthy
  sonarstagingdatabase:
    image: postgres:latest
    container_name: sonar-staging-db
    restart: unless-stopped
    volumes:
      - sonar-staging-db-data:/var/lib/postgresql/data:rw
    env_file:
      - .env
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '--host=localhost',
          '--username=${POSTGRES_USER}',
          '--dbname=${POSTGRES_DB}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

volumes:
  sonar-staging-db-data:
  
