services:
  sonardevbackend:
    image: dimagin/sonar-back:latest
    container_name: sonar-dev-back
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      sonardevdatabase:
        condition: service_healthy
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonar-dev-back.rule=Host(`${SONAR_DEV_BACKEND_HOST}`)
      - traefik.http.routers.sonar-dev-back.entrypoints=websecure
      - traefik.http.routers.sonar-dev-back.tls=true
      - traefik.http.routers.sonar-dev-back.tls.certresolver=cloudflare
      - traefik.http.services.sonar-dev-back.loadbalancer.server.port=3000
      - traefik.http.routers.sonar-dev-back.service=sonar-dev-back
      - traefik.http.routers.sonar-dev-back.tls.options=default
  sonardevdatabase:
    image: postgres:latest
    container_name: sonar-dev-db
    restart: unless-stopped
    volumes:
      - sonar-dev-db-data:/var/lib/postgresql/data:rw
    networks:
      - traefik-network
    env_file:
      - .env
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '--host=localhost',
          '--username=${POSTGRES_USER}',
          '--dbname=${POSTGRES_DB}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.sonar-dev-db.rule=HostSNI(`${SONAR_DEV_DB_HOST}`)
      - traefik.tcp.routers.sonar-dev-db.entrypoints=postgresql
      - traefik.tcp.routers.sonar-dev-db.tls=true
      - traefik.tcp.routers.sonar-dev-db.tls.certresolver=cloudflare
      - traefik.tcp.services.sonar-dev-db.loadbalancer.server.port=5432
      - traefik.tcp.routers.sonar-dev-db.service=sonar-dev-db

networks:
  traefik-network:
    external: true

volumes:
  sonar-dev-db-data:
