services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8090:3000'
    env_file:
      - .env
    volumes:
      - web-data:/app:rwz
      - db-data:/app/db:rw
    depends_on:
      - db
    networks:
      - sonar

  db:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - sonar
    env_file:
      - .env

networks:
  sonar:
    driver: bridge

volumes:
  db-data:
  web-data:
