services:
  backend:
    image: dimagin/sonar-back:latest
    container_name: sonar-back
    user: '${UID}:${GID}'
    restart: unless-stopped
    ports:
      - ${SONAR_PORT}:3000
    env_file:
      - .env
    volumes:
      - sonar-app-data:/app:rw
    depends_on:
      - db
    networks:
      - sonar-network

  db:
    image: postgres:latest
    container_name: sonar-db
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - sonar-db-data:/var/lib/postgresql/data:rw
    networks:
      - sonar-network
    env_file:
      - .env

networks:
  sonar-network:
    driver: bridge

volumes:
  sonar-db-data:
  sonar-app-data:
