services:
  web:
    image: sonar-back:v1
    restart: unless-stopped
    ports:
      - '8090:3000'
    env_file:
      - .env
    volumes:
      - web-data:/app:rwz
    depends_on:
      - db
    networks:
      - sonar

  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: sonar-db
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ./data:/var/lib/postgresql/data:rwz
    networks:
      - sonar

networks:
  sonar:
    driver: bridge

volumes:
  db-data:
  web-data:
