name: Deploy to Production

on:
  workflow_run:
    workflows: ['Build and Publish Docker Image']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy the docker-compose file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd sonar-back
            curl -o docker-compose.yaml https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/master/docker-compose.yaml
            if [ ! -f docker-compose.yaml ]; then
              echo "Erreur : le fichier docker-compose.yaml n'a pas été téléchargé !" >&2
              exit 1
            fi

      - name: Run the docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd sonar-back
            UID=$(id -u) GID=$(id -g) docker compose down
            UID=$(id -u) GID=$(id -g) docker compose pull
            UID=$(id -u) GID=$(id -g) docker compose up -d --force-recreate
