name: Deploy to Production

on:
  workflow_run:
    workflows: ['Build and Publish Docker Image']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the docker-compose file
        uses: appleboy/ssh-action@master
        env:
          REPO_OWNER: ${{ github.event.repository.owner.name }}
          REPO_NAME: ${{ github.event.repository.name }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd sonar-back
            curl -O https://raw.githubusercontent.com/$REPO_OWNER/$REPO_NAME/master/docker-compose.yml || exit 1

      - name: Run the docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd sonar-back
            UID=$(id -u) GID=$(id -g) docker compose down
            UID=$(id -u) GID=$(id -g) docker compose pull
            UID=$(id -u) GID=$(id -g) docker compose up -d --force-recreate
