name: Deploy to Staging

on:
  push:
    branches: ['Ryan']
  pull_request:
    branches: ['Ryan']
  workflow_run:
    workflows: ['docker-staging-image.yml']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Copy the docker-compose file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd sonar-back-staging
            curl -o docker-compose.yaml https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/Ryan/docker-compose-staging.yaml

      - name: Run the docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd sonar-back-staging
            docker compose down
            docker compose pull
            docker compose up -d
