name: Build and Publish Docker Staging Image

on:
  push:
    branches:
      - Ryan

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to docker hub
        id: docker-hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker Image
        id: build-image
        run: |
          docker build --target staging -t ${{ secrets.DOCKER_USERNAME }}/sonar-back:staging .

      - name: Push the Docker image
        id: push-image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sonar-back:staging
